name: Failing Job
on: [workflow_dispatch, pull_request, push]
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first"
  job-two:
    runs-on: ubuntu-latest
    needs: job-one
    steps:
      - run: echo "second" && exit 1
  retry-three:
    runs-on: ubuntu-latest
    needs: job-two
    steps:
      - run: echo "third"
